manta_cam_node:
  ros__parameters:
    device_id: 50-0503464778
    acquire: true
    exposure_auto: "Continuous" # options Off, Once, Continuous
    gain_auto: "Continuous" # options Off, Once, Continuous
    exposure_time_abs: 2000.0 # (us) min 0.0 max 1e6
    gain: 300.0 # (%) min 0.0 max 10000.0
    acquisition_mode: "Continuous" # options Continous, SingleFrame, MultiFrame
    acquisition_frame_rate: 10.0 # (hz) min 0.0 max 1000.0
    trigger_mode: "Off" # options Off, On
    trigger_source: "Line1" # options Software, Line1, Line2
    trigger_rate: 100.0 # (hz) min 0.01 max 200.0
    focus_pos: 32767 # min 0 max 65535
    frame_id: "camera"
    gev_scps_packet_size: 9000  # options 1500, 576, 9000 (e.g. mtu)
    pixel_format: "RGB8" # options RGB, Mono8, Mono12, Mono12Packed, YUV422Packed, etc
    target_brightness: 100 # min 0 max 100